Further changes

diff --git a/salt/bin/provision b/salt/bin/provision
--- a/salt/bin/provision
+++ b/salt/bin/provision
@@ -1,8 +1,14 @@
 #!/bin/bash
 
+no_check=false
 case "$1" in
-run)
-	shift
+--no-check)
+        no_check=true
+        shift
+        ;;
+esac
+runit()
+{
 	case "$#" in
 	0)
 		echo "Running all states ..."
@@ -16,6 +22,33 @@ run)
 		done
 		;;
 	esac
+}
+case "$1" in
+run)
+	shift
+        if $no_check; then
+                # Color is used when there is no checking (piped output)
+                runit "$@"
+                exit
+        fi
+        runit "$@" 2>&1 | tee /tmp/t$$
+        echo
+        echo Checking results log:
+        ret=
+        if egrep '^\[ERROR *\]' /tmp/t$$; then
+                echo ERROR: `egrep '^\[ERROR *\]' /tmp/t$$ | wc -l` ERRORS FOUND IN LOG
+                ret=1
+        fi
+        if egrep '^ *Result: *False' /tmp/t$$ > /dev/null; then
+                echo 'WARNING (' `egrep '^ *Result: *False' /tmp/t$$ | wc -l` 'Results where False in log)'
+                ret=${ret:-2}
+        fi
+        if [ -z "$ret" ] ; then
+                echo SUCCESS
+        fi
+        rm -f /tmp/t$$
+        exit $ret
+
 	;;
 grains)
 	sudo salt-call grains.items
@@ -26,11 +59,15 @@ pillar)
 packages)
 	dpkg --get-selections | sed -n 's/\s\s*install//p'
 	;;
+search)
+        aptitude search "$@"
+        #apt-cache search "$@"
+        ;;
 install|remove|purge|update|upgrade|clean|autoremove)
 	sudo apt-get "$@"
 	;;
 *)
-	echo "usage: $0 grains|pillar|run [state]|packages|install package|remove package|purge package|autoclean|autoremove\n"
+	echo "usage: $0 grains|pillar|run [state]|packages|search|install package|remove package|purge package|autoclean|autoremove\n"
 	;;
 esac
 		
